on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Validate secrets in the repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm package
        run: npm install

      - name: Test the action
        id: test
        uses: ./
        with:
          files: |-
            test.yaml
          gh_token: ${{ secrets.SECRET_VALIDATION_TOKEN }}
          verbose: "true"

      - name: Test secret exists
        run: echo ${{ secrets.TEST_SECRET }}

      - name: Test secret does not exist
        run: echo ${{ secrets.TEST_SECRET_2 }}

      - name: Test var exists
        run: echo ${{ vars.TEST_VAR }}

      - name: Test var does not exist
        run: echo ${{ vars.TEST_VAR_2 }}

      # Use the output from the `test` step
      - name: Get the output time
        run: echo "The time was ${{ steps.test.outputs.time }}"

      - name: Get the output files
        run: echo "The files were ${{ steps.test.outputs.missing_files }}"
